/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frames;

import entidades.Categoria;
import entidades.Producto;
import entidades.Proveedor;
import excepciones.NegocioException;
import implementaciones.CategoriasNegocio;
import implementaciones.ProveedoresNegocio;
import interfaces.ICategoriasNegocio;
import interfaces.IProductosNegocio;
import interfaces.IProveedoresNegocio;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Rios
 */
public class DlgModificarProducto extends javax.swing.JDialog {

    private Producto producto;
    private ICategoriasNegocio categoriasNegocio;
    private IProveedoresNegocio proveedoresNegocio;
    private IProductosNegocio productosNegocio;
    private List<Proveedor> listaProveedores;
    private List<Categoria> listaCategorias;
    private DefaultComboBoxModel modeloProveedores;
    private DefaultComboBoxModel modeloCategorias;
    
    /**
     * Creates new form DlgModificarProducto
     */
    public DlgModificarProducto(java.awt.Frame parent, boolean modal, Producto producto) {
        super(parent, modal);
        initComponents();
        this.producto = producto;
        this.proveedoresNegocio = new ProveedoresNegocio();
        this.categoriasNegocio = new CategoriasNegocio();
        modeloProveedores = (DefaultComboBoxModel) this.comboProveedor.getModel();
        modeloCategorias = (DefaultComboBoxModel) this.comboCategoria.getModel();
        llenarCampos();
        listarProveedores();
        listarCategorias();
    }
    
    public void llenarCampos(){
        this.txtID.setText(producto.getId().toString());
        this.txtNombre.setText(producto.getNombre());
        this.txtProveedor.setText(producto.getProveedor().getId().toString());
        this.txtPCompra.setText(producto.getPrecio_compra().toString());
        this.txtPVenta.setText(producto.getPrecio_venta().toString());
        this.txtCategoria.setText(producto.getCategoria().getId().toString());
        this.txtCodigo.setText(producto.getCodigo().toString());
        this.txtStock.setText(producto.getStock().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtPCompra = new javax.swing.JTextField();
        txtPVenta = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        lblApartado = new javax.swing.JLabel();
        lblLogoCabecera = new javax.swing.JLabel();
        FondoTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        comboCategoria = new javax.swing.JComboBox<>();
        comboProveedor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtID.setEditable(false);
        jPanel1.add(txtID);
        txtID.setBounds(50, 75, 50, 22);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(80, 105, 170, 30);

        txtProveedor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProveedorKeyTyped(evt);
            }
        });
        jPanel1.add(txtProveedor);
        txtProveedor.setBounds(90, 145, 160, 21);

        txtPCompra.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCompraKeyTyped(evt);
            }
        });
        jPanel1.add(txtPCompra);
        txtPCompra.setBounds(110, 175, 140, 21);

        txtPVenta.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtPVenta);
        txtPVenta.setBounds(100, 205, 150, 21);

        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCategoria);
        txtCategoria.setBounds(90, 235, 160, 21);

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(80, 265, 170, 21);

        txtStock.setEditable(false);
        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jPanel1.add(txtStock);
        txtStock.setBounds(70, 295, 180, 21);

        btnMenu.setBackground(new java.awt.Color(110, 88, 68));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("🏠");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu);
        btnMenu.setBounds(0, 0, 40, 30);

        lblApartado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApartado.setForeground(new java.awt.Color(255, 255, 255));
        lblApartado.setText("Modificar");
        jPanel1.add(lblApartado);
        lblApartado.setBounds(50, 0, 100, 30);

        lblLogoCabecera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogoCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_principal.png"))); // NOI18N
        jPanel1.add(lblLogoCabecera);
        lblLogoCabecera.setBounds(80, 0, 190, 30);

        FondoTitulo.setBackground(new java.awt.Color(110, 88, 68));
        jPanel1.add(FondoTitulo);
        FondoTitulo.setBounds(0, 0, 280, 30);

        jLabel1.setText("Stock :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 300, 50, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese los datos a actualizar");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 200, 20);

        jLabel3.setText("ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 30, 16);

        jLabel4.setText("Nombre :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 60, 16);

        jLabel5.setText("Proveedor :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 16);

        jLabel6.setText("Precio Compra :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 90, 16);

        jLabel7.setText("Precio Venta :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 210, 80, 16);

        jLabel8.setText("Categoría :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 240, 70, 16);

        jLabel9.setText("Código :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 270, 60, 16);

        btnAceptar.setBackground(new java.awt.Color(255, 145, 77));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(20, 330, 72, 30);

        btnCancelar.setBackground(new java.awt.Color(255, 145, 77));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(170, 330, 80, 30);

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel1.add(comboCategoria);
        comboCategoria.setBounds(370, 160, 130, 22);

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecione" }));
        jPanel1.add(comboProveedor);
        comboProveedor.setBounds(370, 120, 130, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
//        Long id_producto = Long.parseLong(txtID.getText());
//        String nombre = txtNombre.getText();
//        Long id_proveedor = Long.parseLong(txtProveedor.getText());
//        Double precio_compra = Double.parseDouble(txtPCompra.getText());
//        Double precio_venta = Double.parseDouble(txtPVenta.getText());
//        Long categoria = Long.parseLong(txtCategoria.getText());
//        Long codigo = Long.parseLong(txtCodigo.getText());
//        Long stock = Long.parseLong(txtStock.getText());
//        
//        producto = new Producto(nombre, id_proveedor, precio_compra, precio_venta, categoria,codigo);
//        productosNegocio.actualizar(producto);
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (txtNombre.getText().length() >= 100 || !Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorKeyTyped

    private void txtPCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCompraKeyTyped
        char c = evt.getKeyChar();
        String codigo = txtPCompra.getText() + c;
        Pattern patron = Pattern.compile("^\\d{0,6}(\\.\\d{0,2})?$");

        Matcher matcher = patron.matcher(codigo);

        if (!matcher.matches() || txtPCompra.getText().length() == 7) {
            evt.consume(); //Si no coincide va a hacer esto: 
        }
    }//GEN-LAST:event_txtPCompraKeyTyped

    private void txtPVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPVentaKeyTyped
        char c = evt.getKeyChar();
        String codigo = txtPVenta.getText() + c;
        Pattern patron = Pattern.compile("^\\d{0,6}(\\.\\d{0,2})?$");

        Matcher matcher = patron.matcher(codigo);

        if (!matcher.matches() || txtPVenta.getText().length() == 7) {
            evt.consume(); //Si no coincide va a hacer esto: 
        }
    }//GEN-LAST:event_txtPVentaKeyTyped

    private void txtCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void listarProveedores() {
        try {
            this.listaProveedores = proveedoresNegocio.consultarTodos();

            for (Proveedor proveedor : listaProveedores) {
                modeloProveedores.addElement(proveedor.getNombre());
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listarCategorias() {
        try {
            this.listaCategorias = categoriasNegocio.consultarTodos();

            for (Categoria categoria : listaCategorias) {
                modeloCategorias.addElement(categoria.getNombre());
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgModificarProducto dialog = new DlgModificarProducto(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FondoTitulo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApartado;
    private javax.swing.JLabel lblLogoCabecera;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPCompra;
    private javax.swing.JTextField txtPVenta;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
