/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frames;

import entidades.Categoria;
import entidades.Producto;
import entidades.Proveedor;
import excepciones.NegocioException;
import implementaciones.CategoriasNegocio;
import implementaciones.ProductosNegocio;
import implementaciones.ProveedoresNegocio;
import interfaces.ICategoriasNegocio;
import interfaces.IProductosNegocio;
import interfaces.IProveedoresNegocio;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Rios
 */
public class DlgProducto extends javax.swing.JDialog {

    private Producto productoActualizar;
    private ICategoriasNegocio categoriasNegocio;
    private IProveedoresNegocio proveedoresNegocio;
    private IProductosNegocio productosNegocio;
    private List<Proveedor> listaProveedores;
    private List<Categoria> listaCategorias;
    private DefaultComboBoxModel modeloProveedores;
    private DefaultComboBoxModel modeloCategorias;
    
    /**
     * Creates new form DlgModificarProducto
     */
    public DlgProducto(java.awt.Frame parent, boolean modal, Producto producto) {
        super(parent, modal);
        initComponents();
        productosNegocio = new ProductosNegocio();
        this.productoActualizar = producto;
        this.proveedoresNegocio = new ProveedoresNegocio();
        this.categoriasNegocio = new CategoriasNegocio();
        modeloProveedores = (DefaultComboBoxModel) this.comboProveedor.getModel();
        modeloCategorias = (DefaultComboBoxModel) this.comboCategoria.getModel();
        
        llenarCampos();
        listarProveedores();
        listarCategorias();
    }
    
    public DlgProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        productosNegocio = new ProductosNegocio();
        this.proveedoresNegocio = new ProveedoresNegocio();
        this.categoriasNegocio = new CategoriasNegocio();
        modeloProveedores = (DefaultComboBoxModel) this.comboProveedor.getModel();
        modeloCategorias = (DefaultComboBoxModel) this.comboCategoria.getModel();
        txtCodigo.setEditable(true);
        listarProveedores();
        listarCategorias();
    }
    
    
    
    private void llenarCampos(){
        this.txtID.setText(productoActualizar.getId().toString());
        this.txtNombre.setText(productoActualizar.getNombre());
        this.txtPCompra.setText(productoActualizar.getPrecio_compra().toString());
        this.txtPVenta.setText(productoActualizar.getPrecio_venta().toString());
        this.txtCodigo.setText(productoActualizar.getCodigo().toString());
        this.txtStock.setText(productoActualizar.getStock().toString());
        modeloProveedores.setSelectedItem(productoActualizar.getProveedor().getNombre());
        modeloCategorias.setSelectedItem(productoActualizar.getCategoria().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPCompra = new javax.swing.JTextField();
        txtPVenta = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        lblApartado = new javax.swing.JLabel();
        lblLogoCabecera = new javax.swing.JLabel();
        FondoTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboProveedor = new javax.swing.JComboBox<>();
        comboCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtID.setEditable(false);
        jPanel1.add(txtID);
        txtID.setBounds(50, 75, 50, 22);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(80, 105, 170, 30);

        txtPCompra.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPCompraKeyTyped(evt);
            }
        });
        jPanel1.add(txtPCompra);
        txtPCompra.setBounds(110, 175, 140, 21);

        txtPVenta.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtPVenta);
        txtPVenta.setBounds(100, 205, 150, 21);

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(80, 265, 170, 21);

        txtStock.setEditable(false);
        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel1.add(txtStock);
        txtStock.setBounds(70, 295, 180, 21);

        lblApartado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApartado.setForeground(new java.awt.Color(255, 255, 255));
        lblApartado.setText("Producto");
        jPanel1.add(lblApartado);
        lblApartado.setBounds(10, 0, 100, 30);

        lblLogoCabecera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogoCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_header.png"))); // NOI18N
        jPanel1.add(lblLogoCabecera);
        lblLogoCabecera.setBounds(60, 0, 210, 30);

        FondoTitulo.setEditable(false);
        FondoTitulo.setBackground(new java.awt.Color(110, 88, 68));
        jPanel1.add(FondoTitulo);
        FondoTitulo.setBounds(0, 0, 286, 30);

        jLabel1.setText("Stock :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 300, 50, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese los datos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 40, 120, 20);

        jLabel3.setText("ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 30, 16);

        jLabel4.setText("Nombre :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 60, 16);

        jLabel5.setText("Proveedor :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 16);

        jLabel6.setText("Precio Compra :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 90, 16);

        jLabel7.setText("Precio Venta :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 210, 80, 16);

        jLabel8.setText("Categoría :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 240, 70, 16);

        jLabel9.setText("Código :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 270, 60, 16);

        btnAceptar.setBackground(new java.awt.Color(255, 145, 77));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(10, 340, 72, 30);

        btnCancelar.setBackground(new java.awt.Color(255, 145, 77));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(190, 340, 80, 30);

        jPanel2.setBackground(new java.awt.Color(0, 145, 155));
        jPanel2.setLayout(null);

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecione" }));
        jPanel2.add(comboProveedor);
        comboProveedor.setBounds(80, 75, 130, 22);

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel2.add(comboCategoria);
        comboCategoria.setBounds(80, 165, 130, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 70, 260, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (productoActualizar != null) {
            if (validarCampos()) {
                productoActualizar.setNombre(txtNombre.getText());
                productoActualizar.setPrecio_compra(Double.parseDouble(txtPCompra.getText()));
                productoActualizar.setPrecio_venta(Double.parseDouble(txtPVenta.getText()));
                int indiceProveedor = comboProveedor.getSelectedIndex();
                productoActualizar.setProveedor(listaProveedores.get(indiceProveedor - 1));
                int indiceCategoria = comboCategoria.getSelectedIndex();
                productoActualizar.setCategoria(listaCategorias.get(indiceCategoria - 1));
                productoActualizar.setCodigo(Long.parseLong(txtCodigo.getText()));
                productoActualizar.setStock(Long.parseLong(txtStock.getText()));
                try {
                    int confirmaActualizacion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea actualizar el producto: " + productoActualizar.getNombre() + " ?", "Actualizar producto", JOptionPane.YES_NO_OPTION);
                    if (confirmaActualizacion == 0) {
                        productosNegocio.actualizar(productoActualizar);
                        JOptionPane.showMessageDialog(null, "Se ha actualizado la información del producto", "Actualización exitosa", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }

                } catch (NegocioException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Producto no actualizado", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            if (validarCampos()) {
                String nombre = txtNombre.getText();
                int indiceProveedor = comboProveedor.getSelectedIndex();
                Proveedor proveedor = listaProveedores.get(indiceProveedor - 1);
                Double precioCompra = Double.parseDouble(txtPCompra.getText());
                Double precioVenta = Double.parseDouble(txtPVenta.getText());
                int indiceCategoria = comboCategoria.getSelectedIndex();
                Categoria categoria = listaCategorias.get(indiceCategoria - 1);
                Long codigo = Long.parseLong(txtCodigo.getText());


                Producto productoAgregar = new Producto(nombre, proveedor, precioCompra, precioVenta, categoria, codigo);
                try {
                    productosNegocio.agregar(productoAgregar);
                    JOptionPane.showMessageDialog(null, "Se ha registrado el producto exitosamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (NegocioException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Producto no registrado", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        
        char c = evt.getKeyChar();
            // Verificar si el carácter ingresado es una letra
            if (!Character.isLetter(c) && c != ' ' || txtNombre.getText().length() >= 100) {
                evt.consume(); // Eliminar el carácter ingresado si no es una letra o espacio
            }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPCompraKeyTyped
        char c = evt.getKeyChar();
        String codigo = txtPCompra.getText() + c;
        Pattern patron = Pattern.compile("^\\d{0,6}(\\.\\d{0,2})?$");

        Matcher matcher = patron.matcher(codigo);

        if (!matcher.matches() || txtPCompra.getText().length() == 7) {
            evt.consume(); //Si no coincide va a hacer esto: 
        }
    }//GEN-LAST:event_txtPCompraKeyTyped

    private void txtPVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPVentaKeyTyped
        char c = evt.getKeyChar();
        String codigo = txtPVenta.getText() + c;
        Pattern patron = Pattern.compile("^\\d{0,6}(\\.\\d{0,2})?$");

        Matcher matcher = patron.matcher(codigo);

        if (!matcher.matches() || txtPVenta.getText().length() == 7) {
            evt.consume(); //Si no coincide va a hacer esto: 
        }
    }//GEN-LAST:event_txtPVentaKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || (c == evt.VK_DELETE))) {
            evt.consume(); // Elimina el carácter que no es del 0 al 9
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void listarProveedores() {
        try {
            this.listaProveedores = proveedoresNegocio.consultarTodos();

            for (Proveedor proveedor : listaProveedores) {
                modeloProveedores.addElement(proveedor.getNombre());
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listarCategorias() {
        try {
            this.listaCategorias = categoriasNegocio.consultarTodos();

            for (Categoria categoria : listaCategorias) {
                modeloCategorias.addElement(categoria.getNombre());
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private boolean validarCampos() {
        if (this.txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Compleme el campo nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.txtPCompra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Compleme el campo precio compra", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.txtPVenta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Compleme el campo precio venta", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.comboCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione la categoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.comboProveedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el proveedor", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgProducto dialog = new DlgProducto(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FondoTitulo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApartado;
    private javax.swing.JLabel lblLogoCabecera;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPCompra;
    private javax.swing.JTextField txtPVenta;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
