package frames;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import entidades.Usuario;
import entidades.Venta;
import excepciones.NegocioException;
import implementaciones.VentasNegocio;
import interfaces.IVentasNegocio;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Kevin Rios
 */
public class FrmConsultarVentas extends javax.swing.JFrame {

    private Usuario usuarioLogueado;
    private IVentasNegocio ventasNegocio;
    private DefaultTableModel model;
    private List<Venta> listaVentas = new ArrayList<>();
    private Date fechaInicio;
    private Date fechaFinal;
    
    private Long idVenta;
    private Long idUsuario;
    private String fecha;
    private Double total;
    
    
    /**
     * Creates new form ConsultarVenta
     */
    public FrmConsultarVentas(Usuario usuarioLogeado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioLogueado = usuarioLogeado;
        this.ventasNegocio = new VentasNegocio();
        model = (DefaultTableModel) this.tblVentas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        lblSeleccionarFecha = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        lblApartado = new javax.swing.JLabel();
        lblLogoCabecera = new javax.swing.JLabel();
        FondoTitulo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtBuscarPorID = new javax.swing.JTextField();
        btnMostrarTodas = new javax.swing.JButton();
        btnPorPeriodo = new javax.swing.JButton();
        btnVerDetalles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btnSalir.setBackground(new java.awt.Color(255, 145, 77));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_Slim_Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalir.setInheritsPopupMenu(true);
        btnSalir.setName(""); // NOI18N
        btnSalir.setVerifyInputWhenFocusTarget(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(520, 70, 110, 40);

        tblVentas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Usuario", "Total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVentas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 620, 250);

        lblSeleccionarFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSeleccionarFecha.setText("Introduzca ID:");
        jPanel1.add(lblSeleccionarFecha);
        lblSeleccionarFecha.setBounds(10, 70, 120, 14);

        btnMenu.setBackground(new java.awt.Color(110, 88, 68));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("🏠");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu);
        btnMenu.setBounds(0, 0, 50, 30);

        lblApartado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApartado.setForeground(new java.awt.Color(255, 255, 255));
        lblApartado.setText("Consultar Ventas");
        jPanel1.add(lblApartado);
        lblApartado.setBounds(60, 0, 150, 30);

        lblLogoCabecera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogoCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_principal.png"))); // NOI18N
        jPanel1.add(lblLogoCabecera);
        lblLogoCabecera.setBounds(230, 0, 190, 30);

        FondoTitulo.setBackground(new java.awt.Color(110, 88, 68));
        FondoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoTituloActionPerformed(evt);
            }
        });
        jPanel1.add(FondoTitulo);
        FondoTitulo.setBounds(40, 0, 610, 30);

        btnBuscar.setBackground(new java.awt.Color(255, 145, 77));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscar.setInheritsPopupMenu(true);
        btnBuscar.setName(""); // NOI18N
        btnBuscar.setVerifyInputWhenFocusTarget(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(160, 70, 110, 40);

        txtBuscarPorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarPorIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscarPorID);
        txtBuscarPorID.setBounds(10, 88, 140, 22);

        btnMostrarTodas.setBackground(new java.awt.Color(255, 145, 77));
        btnMostrarTodas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMostrarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_listarVentas.png"))); // NOI18N
        btnMostrarTodas.setText("Listar");
        btnMostrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarTodas);
        btnMostrarTodas.setBounds(280, 70, 110, 40);

        btnPorPeriodo.setBackground(new java.awt.Color(255, 145, 77));
        btnPorPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPorPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_consultarPorPeriodoo.png"))); // NOI18N
        btnPorPeriodo.setText("Período");
        btnPorPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPorPeriodo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPorPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorPeriodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPorPeriodo);
        btnPorPeriodo.setBounds(400, 70, 110, 40);

        btnVerDetalles.setBackground(new java.awt.Color(255, 145, 77));
        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_mirarVenta.PNG"))); // NOI18N
        btnVerDetalles.setText("Detalles de Venta");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerDetalles);
        btnVerDetalles.setBounds(450, 390, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void FondoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoTituloActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtBuscarPorID.getText().isEmpty() || txtBuscarPorID.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID","Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            consultarPorId(Long.parseLong(txtBuscarPorID.getText()));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodasActionPerformed
        consultarTodas();
    }//GEN-LAST:event_btnMostrarTodasActionPerformed

    private void txtBuscarPorIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorIDKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == evt.VK_BACK_SPACE) || (c == evt.VK_DELETE))) {
            evt.consume(); // Elimina el carácter que no es del 0 al 9
        }
    }//GEN-LAST:event_txtBuscarPorIDKeyTyped

    private void btnPorPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorPeriodoActionPerformed
            DlgFechaSelector dlgFechaS = new DlgFechaSelector(this, true);
        dlgFechaS.setVisible(true);
        while (dlgFechaS.isVisible()) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException io) {
                io.printStackTrace();
            }
        }
        
        fechaInicio = dlgFechaS.obtenerFechaInicio();
        fechaFinal = dlgFechaS.obtenerFechaFinal();
        System.out.println(fechaInicio + " " + fechaFinal);
        consultarPeriodo(fechaInicio, fechaFinal);
    }//GEN-LAST:event_btnPorPeriodoActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        int indiceFilaSeleccionada = tblVentas.getSelectedRow();
        idVenta = (Long)modelo.getValueAt(indiceFilaSeleccionada, 0);
        idUsuario = (Long)modelo.getValueAt(indiceFilaSeleccionada, 1);
        fecha = (String)modelo.getValueAt(indiceFilaSeleccionada, 2);
        total = (Double)modelo.getValueAt(indiceFilaSeleccionada, 3);
        System.out.println(idVenta + " " + idUsuario + " " + fecha + " " + total);
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    
    public void consultarPeriodo(Date fechaInicial, Date fechaFinal) {
        try {
            this.listaVentas = ventasNegocio.consultarPorPeriodo(fechaInicial, fechaFinal);
            model.setRowCount(0);
            for (Venta ventas : listaVentas) {
                Long id_venta = ventas.getId();
                Long id_usuario = ventas.getUsuario().getId();
                String fecha = String.valueOf(ventas.getFechaDeVenta());
                Double total = ventas.getTotal();
                //llenando la tabla.
                Object[] fila = {id_venta, id_usuario, fecha, total};
                model.addRow(fila);
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void consultarTodas(){
        try {
            this.listaVentas = ventasNegocio.consultarTodos();
            model.setRowCount(0);

            for (Venta ventas : listaVentas) {
                Long id_venta = ventas.getId();
                Long id_usuario = ventas.getUsuario().getId();
                String fecha = String.valueOf(ventas.getFechaDeVenta());
                Double total = ventas.getTotal();
                //llenando la tabla.
                Object[] fila = {id_venta, id_usuario, fecha, total};
                model.addRow(fila);
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void consultarPorId(Long id) {
        try {
            Venta venta = ventasNegocio.consultarPorId(id);
            model.setRowCount(0);
            Long id_venta = venta.getId();
            Long id_usuario = venta.getUsuario().getId();
            String fecha = String.valueOf(venta.getFechaDeVenta());
            Double total = venta.getTotal();
            //llenando la tabla.
            Object[] fila = {id_venta, id_usuario, fecha, total};
            model.addRow(fila);

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmConsultarVentas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FondoTitulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMostrarTodas;
    private javax.swing.JButton btnPorPeriodo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApartado;
    private javax.swing.JLabel lblLogoCabecera;
    private javax.swing.JLabel lblSeleccionarFecha;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtBuscarPorID;
    // End of variables declaration//GEN-END:variables
}
