package frames;

import entidades.Categoria;
import entidades.Producto;
import entidades.Proveedor;
import excepciones.NegocioException;
import implementaciones.CategoriasNegocio;
import implementaciones.ProductosNegocio;
import implementaciones.ProveedoresNegocio;
import interfaces.ICategoriasNegocio;
import interfaces.IProductosNegocio;
import interfaces.IProveedoresNegocio;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kevin Rios
 */
public class RegistrarProducto extends javax.swing.JFrame {

    private IProveedoresNegocio proveedoresNegocio;
    private ICategoriasNegocio categoriasNegocio;
    private IProductosNegocio productosNegocio;
    private List<Proveedor> listaProveedores;
    private List<Categoria> listaCategorias;
    private DefaultComboBoxModel modeloProveedores;
    private DefaultComboBoxModel modeloCategorias;

    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarProducto() {
        initComponents();
        this.productosNegocio = new ProductosNegocio();
        this.proveedoresNegocio = new ProveedoresNegocio();
        this.categoriasNegocio = new CategoriasNegocio();
        modeloProveedores = (DefaultComboBoxModel) this.comboProveedor.getModel();
        modeloCategorias = (DefaultComboBoxModel) this.comboCategoria.getModel();
        listarProveedores();
        listarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        lblApartado = new javax.swing.JLabel();
        lblLogoCabecera = new javax.swing.JLabel();
        FondoTitulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblIDProducto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecioCompra = new javax.swing.JLabel();
        txtVenta = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCompra = new javax.swing.JTextField();
        lblPrecioVenta = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        comboProveedor = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelBotones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btnMenu.setBackground(new java.awt.Color(110, 88, 68));
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("🏠");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu);
        btnMenu.setBounds(0, 0, 50, 30);

        lblApartado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblApartado.setForeground(new java.awt.Color(255, 255, 255));
        lblApartado.setText("Registrar Producto");
        jPanel1.add(lblApartado);
        lblApartado.setBounds(60, 0, 170, 30);

        lblLogoCabecera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogoCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_principal.png"))); // NOI18N
        jPanel1.add(lblLogoCabecera);
        lblLogoCabecera.setBounds(230, 0, 190, 30);

        FondoTitulo.setBackground(new java.awt.Color(110, 88, 68));
        FondoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoTituloActionPerformed(evt);
            }
        });
        jPanel1.add(FondoTitulo);
        FondoTitulo.setBounds(40, 0, 610, 30);

        jPanel2.setBackground(new java.awt.Color(0, 145, 155));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel2.setLayout(null);

        lblProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProveedor.setText("Proveedor:");
        jPanel2.add(lblProveedor);
        lblProveedor.setBounds(78, 90, 80, 20);

        txtID.setEditable(false);
        jPanel2.add(txtID);
        txtID.setBounds(170, 25, 60, 22);

        lblIDProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIDProducto.setText("ID Producto:");
        jPanel2.add(lblIDProducto);
        lblIDProducto.setBounds(70, 25, 90, 20);

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria:");
        jPanel2.add(lblCategoria);
        lblCategoria.setBounds(83, 190, 80, 20);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre);
        lblNombre.setBounds(93, 60, 70, 20);

        lblPrecioCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioCompra.setText("Precio de Compra:");
        jPanel2.add(lblPrecioCompra);
        lblPrecioCompra.setBounds(28, 120, 130, 20);

        txtVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVentaKeyTyped(evt);
            }
        });
        jPanel2.add(txtVenta);
        txtVenta.setBounds(170, 155, 140, 22);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre);
        txtNombre.setBounds(170, 60, 330, 22);

        txtCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCompraKeyTyped(evt);
            }
        });
        jPanel2.add(txtCompra);
        txtCompra.setBounds(170, 120, 140, 22);

        lblPrecioVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioVenta.setText("Precio de Venta:");
        jPanel2.add(lblPrecioVenta);
        lblPrecioVenta.setBounds(44, 155, 120, 20);

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel2.add(comboCategoria);
        comboCategoria.setBounds(170, 190, 240, 22);

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel2.add(comboProveedor);
        comboProveedor.setBounds(170, 90, 240, 22);

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(170, 225, 71, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Código:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 225, 60, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 80, 570, 280);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Datos del Producto");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(240, 50, 170, 25);

        btnRegistrar.setBackground(new java.awt.Color(255, 145, 77));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_registrar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setInheritsPopupMenu(true);
        btnRegistrar.setName(""); // NOI18N
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar);
        btnRegistrar.setBounds(250, 370, 110, 90);

        btnSalir.setBackground(new java.awt.Color(255, 145, 77));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setInheritsPopupMenu(true);
        btnSalir.setName(""); // NOI18N
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(490, 370, 110, 90);

        btnCancelar.setBackground(new java.awt.Color(255, 145, 77));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setInheritsPopupMenu(true);
        btnCancelar.setName(""); // NOI18N
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(370, 370, 110, 90);

        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        panelBotones.setLayout(null);
        jPanel1.add(panelBotones);
        panelBotones.setBounds(240, 365, 370, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void FondoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoTituloActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (validarCampos()) {
            String nombre = txtNombre.getText();
            int indiceProveedor = comboProveedor.getSelectedIndex();
            Proveedor proveedor = listaProveedores.get(indiceProveedor - 1);
            Double precioCompra = Double.parseDouble(txtCompra.getText());
            Double precioVenta = Double.parseDouble(txtVenta.getText());
            int indiceCategoria = comboCategoria.getSelectedIndex();
            Categoria categoria = listaCategorias.get(indiceCategoria - 1);
            Long codigo = Long.parseLong(txtCodigo.getText());

            Producto productoAgregar = new Producto(nombre, proveedor, precioCompra, precioVenta, categoria, codigo);
            try {
                productosNegocio.agregar(productoAgregar);                
                JOptionPane.showMessageDialog(null, "Se ha registrado el producto exitosamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } catch (NegocioException ex) {
                Logger.getLogger(RegistrarProducto.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex, "Producto no registrada", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompraKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCompraKeyTyped

    private Proveedor consultarProveedor(String nombre) {
        try {
            Proveedor proveedor = proveedoresNegocio.consultarPorNombre(nombre);
            if (proveedor == null) {
                JOptionPane.showMessageDialog(null, "El proveedor no existe.", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
                return proveedor;
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return null;
    }

    private Categoria consultarCategoria(String nombre) {
        try {
            Categoria categoria = categoriasNegocio.consultarPorNombre(nombre);
            if (categoria == null) {
                JOptionPane.showMessageDialog(null, "La categoria no existe.", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
                return categoria;
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return null;
    }

    private void listarProveedores() {
        try {
            this.listaProveedores = proveedoresNegocio.consultarTodos();

            for (Proveedor proveedor : listaProveedores) {
                modeloProveedores.addElement(proveedor.getNombre());
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listarCategorias() {
        try {
            this.listaCategorias = categoriasNegocio.consultarTodos();

            for (Categoria categoria : listaCategorias) {
                modeloCategorias.addElement(categoria.getNombre());
            }
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void limpiarCampos() {
        this.txtNombre.setText("");
        this.txtCompra.setText("");
        this.txtVenta.setText("");
        this.comboCategoria.setSelectedIndex(0);
        this.comboProveedor.setSelectedIndex(0);
        this.txtCodigo.setText("");
        
    }

    private boolean validarCampos() {
        if (this.txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Compleme el campo nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.txtCompra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Compleme el campo precio compra", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.txtVenta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Compleme el campo precio venta", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.comboCategoria.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione la categoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (this.comboProveedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el proveedor", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void txtVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVentaKeyTyped
//        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.' && txtVenta.getText().length() >= 6) {
//            evt.consume();
//        }
        char c = evt.getKeyChar();
        String codigo = txtVenta.getText() + c;
        Pattern patron = Pattern.compile("^\\d{0,6}(\\.\\d{0,2})?$");

        Matcher matcher = patron.matcher(codigo);

        if (!matcher.matches() || txtVenta.getText().length() == 7) {
            evt.consume(); //Si no coincide va a hacer esto: 
        }
    }//GEN-LAST:event_txtVentaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (txtNombre.getText().length() >= 100 || !Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistrarProducto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FondoTitulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApartado;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblIDProducto;
    private javax.swing.JLabel lblLogoCabecera;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
